# Generated by Django 5.0.3 on 2024-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bzc', '0002_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='notstated', max_length=50),
        ),
    ]
