# Generated by Django 5.0.3 on 2024-04-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bzc', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
